export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SAVE_USER = 'SAVE_USER';
export const REQUEST_MEALS = 'REQUEST_MEALS';
export const RESPONSE_MEALS_SUCCESS = 'RESPONSE_MEALS_SUCCESS';
export const RESPONSE_MEALS_ERROR = 'RESPONSE_MEALS_ERROR';
export const REQUEST_DRINKS = 'REQUEST_DRINKS';
export const RESPONSE_DRINKS_SUCCESS = 'RESPONSE_DRINKS_SUCCESS';
export const RESPONSE_DRINKS_ERROR = 'RESPONSE_DRINKS_ERROR';
export const CLEAN_DRINKS_ERROR = 'CLEAN_DRINKS_ERROR';
export const CLEAN_MEALS_ERROR = 'CLEAN_MEALS_ERROR';
export const REQUEST_RECIPES_MAIN_MEALS = 'REQUEST_RECIPES_MAIN_MEALS';
export const RESPONSE_RECIPES_MAIN_MEALS_SUCCESS = 'RESPONSE_RECIPES_MAIN_MEALS_SUCCESS';
export const RESPONSE_RECIPES_MAIN_MEALS_ERROR = 'RESPONSE_RECIPES_MAIN_MEALS_ERROR';
export const REQUEST_RECIPES_MAIN_DRINKS = 'REQUEST_RECIPES_MAIN_DRINKS';
export const
  RESPONSE_RECIPES_MAIN_DRINKS_SUCCESS = 'RESPONSE_RECIPES_MAIN_DRINKS_SUCCESS';
export const RESPONSE_RECIPES_MAIN_DRINKS_ERROR = 'RESPONSE_RECIPES_MAIN_DRINKS_ERROR';
export const REQUEST_RECIPE_MEALS = 'REQUEST_RECIPE_MEALS';
export const RESPONSE_RECIPE_MEALS_SUCCESS = 'RESPONSE_RECIPE_MEALS_SUCCESS';
export const RESPONSE_RECIPE_MEALS_ERROR = 'RESPONSE_RECIPE_MEALS_ERROR';
export const REQUEST_RECIPE_DRINKS = 'REQUEST_RECIPE_DRINKS';
export const RESPONSE_RECIPE_DRINKS_SUCCESS = 'RESPONSE_RECIPE_DRINKS_SUCCESS';
export const RESPONSE_RECIPE_DRINKS_ERROR = 'RESPONSE_RECIPE_DRINKS_ERROR';

export const REQUEST_RECIPES_CATEGORIES_MEALS = 'REQUEST_RECIPES_CATEGORIES_MEALS';
export const
  RESPONSE_RECIPES_CATEGORIES_MEALS_SUCCESS = 'RESPONSE_RECIPES_CATEGORIES_MEALS_SUCCESS';

export const REQUEST_RECIPES_CATEGORIES_DRINKS = 'REQUEST_RECIPES_CATEGORIES_DRINKS';
export const
  RESPONSE_RECIPES_CATEGORIES_DRINKS_SUCCE = 'RESPONSE_RECIPES_CATEGORIES_DRINKS_SUCCE';

export const REQUEST_MEALS_RECOMMENDATION = 'REQUEST_MEALS_RECOMMENDATION';
export const
  RESPONSE_MEALS_RECOMMENDATION_SUCCESS = 'RESPONSE_MEALS_RECOMMENDATION_SUCCESS';
export const RESPONSE_MEALS_RECOMMENDATION_ERROR = 'RESPONSE_MEALS_RECOMMENDATION_ERROR';
export const REQUEST_DRINKS_RECOMMENDATION = 'REQUEST_DRINKS_RECOMMENDATION';
export const
  RESPONSE_DRINKS_RECOMMENDATION_SUCCESS = 'RESPONSE_DRINKS_RECOMMENDATION_SUCCESS';
export const
  RESPONSE_DRINKS_RECOMMENDATION_ERROR = 'RESPONSE_DRINKS_RECOMMENDATION_ERROR';

export const SAVE_CURRENT_RECIPE = 'SAVE_CURRENT_RECIPE';
